### ISSUE TITLE
stapy 61資料作成

### ISSUE THREAD

**Issue by takanory** [takanory/slides#25]
* 9月10日
* https://startpython.connpass.com/event/186016/

**Comment by takanory** [comment]
* オンライン時代のプログラミング習得
* 最初に書籍の紹介
* COVID-19の影響でいろいろ変わっている気がする
  * なんか書籍が売れているらしい https://www.businessinsider.jp/post-209468
* COVID-19時台のプログラミング習得について考えてみた
  * 大前提: インプット→ためす→アウトプット→フィードバックもらう
* インプットの手段毎にどうだろう?
  * 書籍→前から変わらなそう
  * 動画→前から変わらなそう
  * プログラミングスクール→オンライン対応しているらしい。サポート体制とかどうなんだろう
  * 勉強会→オンラインが増えて参加はしやすくなった。でもつながりが濃くなりにくそう
  * カンファレンス→PyCon JP 2020がオンラインになった
* アウトプットどうするか問題

**Comment by takanory** [comment]
オンライン時代のプログラミング習得について考える

COVID-19の影響でいろいろと生活が変わっていると思いますが、プログラミングを習得する流れについても変わりつつあると感じています。ここ最近のプログラミングを習得するにあたって、どういう動きがあるか、課題となりそうなことについて考えを共有します。みなさんはどう感じているか、意見交換ができるといいなと思っています。

**Comment by drillan** [comment]
> * なんか書籍が売れているらしい https://www.businessinsider.jp/post-209468

じゃあ、技術書(コンピュータ関連)はどうなのか...みたいに話が膨らむとよさそう

**Comment by drillan** [comment]
コミュニティ活動がオフラインからオンラインに変わって、地域の壁がなくなった？ -> 体感的にはそうでもない気がする
オンラインだと常連の人だけが発言しているコミュニティでは、余計に会話に入りにくいかなぁと推測しているけど、実際はどうなんでしょ？

**Comment by YasukiKishi** [comment]
- プログラミングスクール→オンライン対応しているらしい。サポート体制とかどうなんだろう
意見というわけではないのですが、これに対して私の知る限りの情報共有させてください。

プログラミングスクールは、転職支援系とスキルアップ系の２つに事業の方向性が大きく分かれます。
転職支援系では、大手で営業担当などの本社社員リストラをはじめているところが出始めていると聞いています。

IT業界未経験者（誤解を恐れずに言うと情弱な方）をターゲットに「転職成功99％」と謳って集客していますが、実態はCOVID-19以前からも99％は有り得なく、いま未経験者の転職は壊滅的です。
もとよりこういったスクールはカリキュラム途中での脱落者が多く（3割ぐらいと聞いています）、だれでも修了できるように難易度設定をどんどん下げて内容が希薄になっていく傾向がありました。
受講生は教室に集まって仲間意識を高めること（感情報酬を高めるなんて表現されています）でカリキュラム完遂の補完をしようとしていましたが、これもCOVID-19で難しくなりました。
こういった状況で上記の社員リストラが始まっています。

一方でスキルアップ系は好調です。
LE社の調査でもCOVID-19の巣ごもりで新しく始めたこととして、スキルアップの勉強と答えた人は32％いました。
書籍が売れているらしい、と符合すると思います。
カンファレンスや勉強会でも登壇者が聴衆の反応を得られずやりにくい、といったところは同じで大きな課題といえます。
MOOCなどのビデオ教材での学習もCOVID-19以前から話題になっていましたが、根本的には学習モチベーションを維持することへの課題はあります。
こういったことの対策としてオンライン対応しつつも、授業は手書きで手元をカメラで映して講師が直接教える形式にしたりと、オフラインと変わらない感覚で提供しているスクールが受講生からの評価も高いようです。

スキルアップ系の一種となる、趣味と学習のバランスの良いIoT工作系も悪くないです。
画面で教えるプログラミングだけよりも、手元を映して教えたりと動きがあり、受講生からも質問が出やすくオンライン授業として成立しやすい、という要素があるようです。（StartLabもこの利点を考慮してIoTコースを立ち上げました）

**Comment by abenben** [comment]
> * 目的が大事。なんのためにプログラミング習得したいの?
本当ですよね。目的が大事です。
特にエンジニア以外の場合は、Pythonだけ習っても「で、どうしようかな。」ってなるんだと思います。
多分、やりたいことは今の現場の仕事や作業効率を向上したり、エンジニアならば開発の生産性や品質を上げたいんだと思うんですよね。または身の回りに溢れているデータをもっと効率よく整理して可視化や分析などがしたいなど。
周辺知識との連携技術などを習得できるとどんどん発展できると思うんですよね。
いままで使っていたExcelと連携したり、使っている社内システムを自動化したり、スクレイピングしたり、botやslackに自動通知したり、そういったことをどんどん挑戦すると、Pythonがグル言語として大活躍していくはずですが、どうしても既存業務の消化を優先してしまうので、このあたりの勇気というか挑戦が大事と思っています。たかのりさんもPyCon JPでいっぱいツール作ってくれてましたよね。ああいった事をみんなができるといいんですよねー。

**Comment by abenben** [comment]
> * 勉強会→オンラインが増えて参加はしやすくなった。でもつながりが濃くなりにくそう
これ、私達も悩んでます。困っています。

もともとstapyはPython全体の初級・中級者向けのコミュニティなので、そもそも繋がりが薄いんですよね。
なので、コミュニティには、それぞれの役割があってもいいと少し割り切っています。
オフラインの時は、stapyの懇親会を通して新しい仲間ができ、その仲間通しで仕事関係や、クローズドでもいいので何か深いつながりになってもらえてました。そういう人は毎回参加するリピーターではありませんが、自分の好きなテーマの時にまた新しい仲間を探すためだけにstapyに参加してもらえるようなサイクルで来てくれてました。
でも、オンラインでは懇親会をあまり盛り上げれてないんですよねー。なので、メンバー同士で仲間を作ってもらう仕組みがちょっと足りないんですよねー。ここをもっと活性化できると最終的にはPythonの人気持続にどんどんつながるので、間接的に私達もStapyを継続させていくモチベーションに繋がっていきます。

**Comment by takanory** [comment]
書いた
